import "./globals.css";
import Header from "../layout/Header/Header";
import Footer from "@/layout/Footer/Footer";
import Routebar from "@/components/RouteBar/Routebar";
import ScrollToTop from "@/components/ScrollToTop/ScrollToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col"
      >
         <ScrollToTop />
         <Header />
          <div className="flex-grow font-helvetica-light tracking-wide text-[#1E1E1E]">

        {children}
        </div>
            <Routebar />
        <Footer />
      </body>
    </html>
  );
}
